name: FreeTrade
main: com.exphc.FreeTrade.FreeTrade
version: 1
commands:
    want:
        description: Place an order for an item you want
        #permission: freetrade.want
        usage: /want [item you want] for [item you will give in return]
softdepend: [OddItem]
foo: bar
