name: FreeTrade
main: com.exphc.FreeTrade.FreeTrade
version: 1
commands:
    want:
        description: Place an order for an item you want
        #permission: freetrade.want
        aliases: w
        usage: /<command> [item you want] for [item you will give in return]
softdepend: [OddItem]
permissions:
    freetrade.*:
        children:
            freetrade.trade: true
            freetrade.conjure: true
            freetrade.bigstacks: false
        default: true
    freetrade.trade:
        description: Allows you to trade with other players
    freetrade.conjure:
        description: Allows you to create items out of thin air
    freetrade.bigstacks:
        description: Allows you to stack items in any amount
